### ISSUE TITLE
Hi, do you have any interest in developing a similar tool for uber drivers?

### ISSUE THREAD

**Issue by andrelopesmrx** [ummjackson/uber-data-extractor#10]

**Comment by matth3us** [comment]
Is the uber driver profile page too diferent from the customer profile page? It shouldn't take too much trouble to adapt the script if the pages are similar...

**Comment by ummjackson** [comment]
@andrelopesmrx Hey there! I'd be happy to explore this, but would need to have access to an Uber Driver account login, otherwise I can't develop it :)

**Comment by andrelopesmrx** [comment]
The problem is that the driver login requires 2 factor authentication. I
will check if there is a way to disable it.

**Comment by andrelopesmrx** [comment]
I did some research, and apparently there is no way to disable 2FA for
partners.
Developers would need to register themselves as drivers to get access to
the drivers panel


-- 
André Gustavo N. Lopes
Cel: +55 (41) 9162-9521
www.mrx.com.br

**Comment by ummjackson** [comment]
@andrelopesmrx Unfortunately I can't help without that driver access. Sorry!! :(
