### ISSUE TITLE
Uber Driver

### ISSUE THREAD

**Issue by pacpanda** [ummjackson/uber-data-extractor#16]
Hi, I'm new to coding and playing around with data. Also, I am an Uber driver. Trying to find a way to gather all my trip information to analyze the data. 

Can someone please help.

**Comment by lmj0011** [comment]
try using this tool https://github.com/lmj0011/uber-driver-mileage-scraper

**Comment by ummjackson** [comment]
Thanks @lmj0011 - looks good.
