### ISSUE TITLE
Can't get uberPOOL values

### ISSUE THREAD

**Issue by rstacruz** [ummjackson/uber-data-extractor#2]
How can we help to implement this?

**Comment by ummjackson** [comment]
Hmm, it was pulling Pool values fine for me a month or two ago... perhaps they changed the markup of the page. I'll investigate this weekend. If you want to give it a shot yourself, take a look at how the dom is scraped @ https://github.com/ummjackson/uber-data-extractor/blob/master/index.js#L6 - my best guess would be that UberPOOL is rendering a little differently now.

**Comment by ummjackson** [comment]
@rstacruz - I tested this on my account and it worked fine, all of my UberPOOL rides were represented as rows in the outputted CSV. Are the rows missing entirely for you?

**Comment by rstacruz** [comment]
It was showing a blank value for where the amount should be. By the way,
I'm in the Philippines and the currency format is "PHP 80.00" if that
helps!

**Comment by ummjackson** [comment]
@rstacruz Ahh, I've seen this issue... it's to do with the formatting of the field and sometimes there is a little icon injected in the field which can cause issues. I'll play around with it and see if it can be fixed by targeting a more specific child element in the DOM. Also open to pull requests if you feel like giving it shot yourself :)

**Comment by ummjackson** [comment]
@rstacruz So I tried reproducing this based on trips I had while back in Australia... the cost is represented as A$10.00 and works fine, so I'm stumped as to why it's breaking in the Philippines. Can you give the bookmarklet a try again and see if it still breaks? Is it breaking for *all* trips or just UberPOOL specifically. 

One thing I noticed was that it does return a blank entry for cancelled trips. Are you 100% certain you weren't looking at *cancelled* UberPOOL trips and those were empty?

**Comment by ummjackson** [comment]
Closing for now as I can't replicate... @rstacruz let me know if you have further details.
