### ISSUE TITLE
Chrome Content Security Policy directive

### ISSUE THREAD

**Issue by JohnMcLear** [ummjackson/uber-data-extractor#5]
```
Refused to load the script 'https://medialab.github.io/artoo/public/dist/artoo-latest.min.js' because it violates the following Content Security Policy directive: "script-src 'nonce-40de9846-41ea-4fe3-bd56-9d3c724fdd8c' 'self' 'unsafe-inline' 'unsafe-eval' https://analytics.recruitics.com https://cdn.mxpnl.com https://www.google-analytics.com https://ssl.google-analytics.com https://js.braintreegateway.com https://tags.tiqcdn.com https://secure.quantserve.com https://www.googleadservices.com https://connect.facebook.net".
```

**Comment by ummjackson** [comment]
Hmm, https://medialab.github.io/artoo/public/dist/artoo-latest.min.js still resolves so I'm guessing Uber might have changed something on their end. I'll debug this some more.

**Comment by lklots** [comment]
temporary hack: copy and paste the url payload into the console directly. so first copy and paste https://code.jquery.com/jquery-2.1.3.min.js to the console and then the payload at https://medialab.github.io/artoo/public/dist/artoo-latest.min.js

**Comment by ummjackson** [comment]
@JohnMcLear / @lklots In my testing on the latest Stable channel release of Chrome on macOS the bookmarklet still works, and I don't receive any issues with the script refusing to load. 

Do you by chance have some ad blockers or other plugins enabled? This might be causing the issue.

**Comment by febzz** [comment]
Copy-pasting the 2 js files into the Console so far makes it work again. Thanks, @lklots !

**Comment by jausling** [comment]
+1 on all this - the .js files worked for me on chrome - closing my other issue

**Comment by ummjackson** [comment]
@jausling I can't reproduce this issue. Are you on Mac/Win? Do you have any ad-block extensions disabled?

**Comment by ummjackson** [comment]
... scratch that, I can now reproduce. Weird! Will look into a potential fix for this.

**Comment by nitos** [comment]
@ummjackson hey, how can you add those files? I never use the console so, I'm really new to this. Thanks!

**Comment by pookeye** [comment]
thanks again to lklots,  that worked!

**Comment by a1a1k1k1** [comment]
Hi Ummjackson,

Thank you for developing this awesome bookmarklet.. I have been trying to make this work on my account for the last month but it doesnt work. Have tried it on  Chrome, mozilla even edge and IE on 2 different pcs (windows 10 and 7). Disabled ad/popup blockers and antivirus. 

After I click on uber export and nothing really happens. I am not an extensive coder... Your help will be much appreciated.

JohnMcLear: apologies for using your issue chat to bring this up..,

**Comment by Californian** [comment]
@a1a1k1k1
1. Open https://riders.uber.com/trips.
2. Open the links posted in [the above comment](https://github.com/ummjackson/uber-data-extractor/issues/5#issuecomment-328015911) in new tabs.
2. Select all text from one of the pages you just opened, and copy it. It should just be a lot of seemingly-random text (javascript).
3. Go to the uber tab.
4. Press Ctrl-Shift-J (or Cmd-Shift-J if on Mac, I think). A sidebar or something on the bottom should pop up.
5. Paste the really long text.
6. Press enter.
7. Do steps 2-6 again, but with the second link.
8. Go back to the uber tab.
9. Click the bookmarklet.
10. It should say `[artoo]: debug - Starting the scraper...` in the sidebar thing at the end. If so, wait for a while, and it should complete as expected.

**Comment by a1a1k1k1** [comment]
@Californian Thank you for the detailed steps. Much appreciated. This worked for me!

**Comment by ummjackson** [comment]
Thanks for the walkthrough @Californian - it seems that this is Uber enforcing CSP on their domain now... the only real workaround would be to evolve this into a Chrome extension, but that seems a bit heavy for this task. If you have any ideas, appreciated.

**Comment by ummjackson** [comment]
Good news everyone! @JohnMcLear @lklots @febzz @jausling @pookeye 

I have been able to port the bookmarklet to a Chrome extension in this branch: https://github.com/ummjackson/uber-data-extractor/tree/chrome-extension

For now, you can manually install the unpackaged extension fairly easily. It should be on the Chrome Web Store in the next few days, too! :)

Thanks for your patience, glad I can finally close this issue. 👍 (will leave open until I can redirect people to the Chrome store URL)

**Comment by ummjackson** [comment]
Now on the Chrome Web Store: https://chrome.google.com/webstore/detail/uber-data-extractor/ckncaneeemafoonmpammikboiakeaggp

Closing issue, thanks all.
