### ISSUE TITLE
Uber Export link no longer working

### ISSUE THREAD

**Issue by SamSohNZ** [ummjackson/uber-data-extractor#8]
Hi - The Uber Export link no longer scraps my rides

**Comment by fearthedear** [comment]
Hey @SamSohNZ - see the other open issue #5 , it is most likely a problem with the Chrome Content Security Policy. Basically you need to copy paste two scripts into the console, see the other issue #5  for details. Can be closed.

**Comment by SamSohNZ** [comment]
For the newbies.
1. Browse to https://riders.uber.com/trips.
2. In Chrome, press F12 > Click Console Tab.
3. Copy and paste code the following codes into the console > Press Enter
https://code.jquery.com/jquery-2.1.3.min.js
https://medialab.github.io/artoo/public/dist/artoo-latest.min.js
4. Click your Uber Export shortcut again.
5. Have a Beer

**Comment by harley9** [comment]
Will this work for the driver's ride history as well?  Or is there another script to download/scrap the an Uber Partner's history?

**Comment by ummjackson** [comment]
@harley9 This is just for the riders, not for drivers. I don't have access to a driver account so haven't been able to build that version, unfortunately.
