### ISSUE TITLE
Bookmarklet broken on latest version of Chrome (Version 63.0.3239.132)

### ISSUE THREAD

**Issue by nsafai** [ummjackson/uber-data-extractor#9]
Tried using today using instructions from your github repo. No message appeared to indicate that scraping was in progress.

**Comment by ummjackson** [comment]
Hi there, 

Please use the Chrome extension (https://chrome.google.com/webstore/detail/uber-data-extractor/ckncaneeemafoonmpammikboiakeaggp) that is now the default branch of this repo. 

The bookmarklet no longer works as Uber is not allowing the script to be injected. The extension works around this. 

Thanks,
Jackson.
